### PR TITLE
Skip `power_assert` 3.0 on Ruby < 3.1`

### PR DESCRIPTION
**Pull request by Earlopain**
It requires Ruby 3.1 but declares no `required_ruby_version`. Ref: https://github.com/test-unit/test-unit/pull/329#issuecomment-3484622030

https://github.com/ruby/prism/pull/3704
https://github.com/ruby/prism/actions/runs/19042061678/job/54381447946
> /Users/runner/hostedtoolcache/Ruby/2.7.8/arm64/lib/ruby/gems/2.7.0/gems/onigmo-0.1.0/lib/onigmo/node.rb:27:in `private_class_method': undefined method `new' for class `#<Class:Onigmo::Node>' (NameError)
Did you mean?  next

https://github.com/ruby/power_assert/releases/tag/v3.0.0
> Drop support for ruby < 3.1

### CODE REVIEW

**Review by kddnewton — APPROVED** [review]

**Comment by Earlopain** [comment]
Waiting so see how https://github.com/ruby/power_assert/pull/61 plays out. Maybe this won't be needed.

**Comment by Earlopain** [comment]
Should just work with `power_assert` 3.0.1
